In [1]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 kB 1.9 MB/s eta 0:00:00
  Obtaining dependency information for simpful from https://files.pythonhosted.org/packages/8d/93/8448d3f1aa9d2911b8cba2602aaa1af85eb31a26d28b7b737f1fa5b40c02/simpful-2.11.1-py3-none-any.whl.metadata
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Created wheel for fst-pso: filename=fst_pso-1.8.1-py3-none-any.whl size=20431 sha256=733246d2ce093db522404efc7688392ba1b29778fb61524bdad64c117c6dbce7
  Stored in directory: /Users/shridharmankar/Library/Caches/pip/wheels/99/66/48/d7ce0c6927f6abf167bbcdee537affc7b92c03632f78028411
  Created wheel for miniful: filename=miniful-0.0.6-py3-none-any.whl size=3513 sha256=780c8e9db9038d38b70f274b43fae7238fbe7071dc66c140c855d7cc472c9570
  Stored in directory: /Users/shridharmankar/Library/Caches/pip/wheels/d9/c7/71/db1d4646d963b34c530667501d3d6f34c0825eaffae2f0f2cb
Successfully built fst-pso miniful


In [118]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [119]:
import pandas as pd

In [120]:
datasett = pd.read_csv('/Users/shridharmankar/review.csv')

In [121]:
datasett

review  label
0            Rocky bhai ‘rocks’, awesome performance.      1
1           It was a good movie, a blockbuster cinema      1
2                        I loved the movie and acting      1
3         Great performance by Yash and ‘Sanju’ baba.      1
4                                Total waste of money      0
5   Poor storyline, and very bad performance by th...      0
6   I Give 9/10 for this one.9/10 Cuz,Editing styl...      1
7                  First half is very slow and boring      0
8        Songs are the best part of movie, I liked it      1
9                                  I didn’t liked it.      0
10            I will give it a big zero, what a waste      0
11                      Total overacting by the leads      0
12  No doubt. This film is the changing phase for ...      1
13  The best of all Indian movies.Nothing can be c...      1
14  Race is known for his suspenses and thriller.....      0
15  #Fresh Story ,Great Visuals,best part is there...      1
16  Worst movie of the Race franchise. It's an all...      0
17        A very illogical action sequences as usual.      0
18  Remarkable direction, outstanding acting, monu...      1
19             Meaningless, in appropriate, boring!!!      0
20  Race 3 is undoubtedly one of the worst big bud...      0
21  This was 3rd class acting from top class actor...      0
22  This is the worst movie I've ever seen in my w...      0
23  An epic milestone in Kannada industry!! I am n...      1
24  Fabulous work done by prashant neel,we can't g...      1
25  KGF is a win for the whole Kannada film industry.      1
26  Even the characters or the performances didn't...      0
27  One does not go to watch the race franchise fo...      0
28  There's a twist a minute and frankly the twist...      0

In [122]:
from nltk.corpus import stopwords
import re
corpus = []
for i in range(0, 29):
    review = re.sub('[^a-zA-Z]', ' ', datasett['review'][i])
    review = review.lower()
    review = review.split() 
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [123]:
corpus

['rocky bhai rock awesome performance',
 'good movie blockbuster cinema',
 'loved movie acting',
 'great performance yash sanju baba',
 'total waste money',
 'poor storyline bad performance lead',
 'give one cuz editing style kinda much fast except everything felt right heart',
 'first half slow boring',
 'song best part movie liked',
 'liked',
 'give big zero waste',
 'total overacting lead',
 'doubt film changing phase sandalwood industry every people put seeminglessly hard work effort',
 'best indian movie nothing compared',
 'race known suspense thriller missing film',
 'fresh story great visuals best part many character film really increase curiosity audience prof hero powerful character movie else movie would become predictable like bollywood masala movie',
 'worst movie race franchise salman khan show giving star',
 'illogical action sequence usual',
 'remarkable direction outstanding acting monumental narration unthinkable screenplay striking action sequence',
 'meaningless app

In [124]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

sentences = []
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        sentences.append(simple_preprocess(sent))

In [125]:
sentences

[['rocky', 'bhai', 'rock', 'awesome', 'performance'],
 ['good', 'movie', 'blockbuster', 'cinema'],
 ['loved', 'movie', 'acting'],
 ['great', 'performance', 'yash', 'sanju', 'baba'],
 ['total', 'waste', 'money'],
 ['poor', 'storyline', 'bad', 'performance', 'lead'],
 ['give',
  'one',
  'cuz',
  'editing',
  'style',
  'kinda',
  'much',
  'fast',
  'except',
  'everything',
  'felt',
  'right',
  'heart'],
 ['first', 'half', 'slow', 'boring'],
 ['song', 'best', 'part', 'movie', 'liked'],
 ['liked'],
 ['give', 'big', 'zero', 'waste'],
 ['total', 'overacting', 'lead'],
 ['doubt',
  'film',
  'changing',
  'phase',
  'sandalwood',
  'industry',
  'every',
  'people',
  'put',
  'seeminglessly',
  'hard',
  'work',
  'effort'],
 ['best', 'indian', 'movie', 'nothing', 'compared'],
 ['race', 'known', 'suspense', 'thriller', 'missing', 'film'],
 ['fresh',
  'story',
  'great',
  'visuals',
  'best',
  'part',
  'many',
  'character',
  'film',
  'really',
  'increase',
  'curiosity',
  'audie

In [126]:
import gensim
model=gensim.models.Word2Vec(sentences,window=3,min_count=1)

In [128]:
model.wv.index_to_key

['movie',
 'film',
 'acting',
 'race',
 'performance',
 'one',
 'industry',
 'boring',
 'best',
 'worst',
 'big',
 'twist',
 'character',
 'belong',
 'liked',
 'part',
 'kannada',
 'song',
 'work',
 'screenplay',
 'heart',
 'whole',
 'seen',
 'action',
 'illogical',
 'sequence',
 'give',
 'story',
 'like',
 'great',
 'franchise',
 'lead',
 'total',
 'waste',
 'khan',
 'salman',
 'class',
 'nothing',
 'every',
 'curiosity',
 'increase',
 'really',
 'people',
 'put',
 'seeminglessly',
 'missing',
 'indian',
 'many',
 'visuals',
 'thriller',
 'suspense',
 'known',
 'fresh',
 'compared',
 'effort',
 'hard',
 'pain',
 'sandalwood',
 'yash',
 'bad',
 'storyline',
 'poor',
 'money',
 'baba',
 'sanju',
 'loved',
 'editing',
 'cinema',
 'blockbuster',
 'good',
 'awesome',
 'rock',
 'bhai',
 'cuz',
 'style',
 'phase',
 'half',
 'changing',
 'doubt',
 'overacting',
 'zero',
 'prof',
 'slow',
 'first',
 'kinda',
 'right',
 'felt',
 'everything',
 'except',
 'fast',
 'much',
 'audience',
 'bollywoo

In [129]:
from gensim.models import KeyedVectors
word_vectors = model.wv
word_vectors.save("word2vec.wordvectors")

wv = KeyedVectors.load("word2vec.wordvectors")
vector = wv['worst']

In [130]:
vector

array([-0.00516135, -0.00665931, -0.00778153,  0.00830611, -0.00198404,
       -0.00688059, -0.00413996,  0.00516614, -0.00288143, -0.00375361,
        0.0016225 , -0.00278295, -0.00158596,  0.00109148, -0.00297067,
        0.00851201,  0.00391102, -0.00997393,  0.00626412, -0.00677479,
        0.0007627 ,  0.0044167 , -0.00509755, -0.00212245,  0.00809876,
       -0.00424117, -0.00763681,  0.00924419, -0.00215651, -0.00472035,
        0.00858634,  0.00429438,  0.00432727,  0.00927229, -0.00845085,
        0.00528137,  0.00203594,  0.00418251,  0.00169582,  0.00444302,
        0.00448896,  0.00608202, -0.00320708, -0.0045686 , -0.00040585,
        0.00254715, -0.00326408,  0.00604743,  0.0041582 ,  0.00776689,
        0.00257371,  0.00810685, -0.00137465,  0.00809005,  0.00371804,
       -0.00803684, -0.00393834, -0.00247364,  0.00487597, -0.00086784,
       -0.00281804,  0.00784027,  0.0093228 , -0.0016121 , -0.0051577 ,
       -0.00470156, -0.00484644, -0.00959649,  0.00135503, -0.00

In [131]:
wv['movie']

array([-5.2999810e-04,  2.2699275e-04,  5.1035010e-03,  8.9984406e-03,
       -9.2795668e-03, -7.1630268e-03,  6.5028626e-03,  9.0146596e-03,
       -5.0565558e-03, -3.7880451e-03,  7.3762988e-03, -1.5634955e-03,
       -4.5611593e-03,  6.5830699e-03, -4.8378794e-03, -1.8307893e-03,
        2.8678293e-03,  9.6426974e-04, -8.2960911e-03, -9.4828401e-03,
        7.3183673e-03,  5.0924504e-03,  6.7691454e-03,  7.3728542e-04,
        6.3626436e-03, -3.4081347e-03, -9.4302942e-04,  5.7585095e-03,
       -7.5121005e-03, -3.9397054e-03, -7.4830614e-03, -9.1826741e-04,
        9.5391916e-03, -7.3387055e-03, -2.3304729e-03, -1.8994625e-03,
        8.0703814e-03, -5.9326421e-03,  3.8138198e-05, -4.8049139e-03,
       -9.5900642e-03,  4.9583502e-03, -8.7575810e-03, -4.3605505e-03,
        3.7428977e-06, -2.7003084e-04, -7.6737590e-03,  9.5948661e-03,
        4.9645063e-03,  9.2443703e-03, -8.1427153e-03,  4.4691125e-03,
       -4.0908633e-03,  8.2141883e-04,  8.4757647e-03, -4.4503375e-03,
      

In [132]:
wv['great']

array([-4.2931000e-03, -9.3107568e-03, -1.8704872e-03, -3.7055428e-03,
        9.1294609e-03,  2.9003946e-03, -5.9485394e-03, -3.3074270e-03,
       -9.9347262e-03,  1.9324863e-03, -3.9820815e-03, -2.7508687e-03,
        5.1695146e-03,  7.6165609e-03,  4.4188746e-03, -6.8403925e-03,
        6.6977432e-03, -9.6435351e-03, -7.0021939e-03, -8.0367653e-03,
       -2.2743531e-03,  4.8561534e-04, -3.7802113e-03,  1.8297629e-03,
        9.2135957e-03,  6.6663558e-03, -1.0757648e-03,  9.0796258e-03,
        1.5408880e-03, -1.9770411e-03, -6.5850154e-03,  6.4880266e-03,
       -9.0613803e-03, -1.9259291e-03,  7.6776068e-03, -2.5686240e-03,
        1.6017010e-03, -7.3419986e-03,  4.9840068e-03,  7.3239030e-03,
       -9.2989681e-03, -3.3049667e-03,  7.8901984e-03,  2.9537512e-03,
        2.5411196e-05,  3.5790939e-04, -9.8683443e-03,  9.9239508e-03,
       -2.0080956e-03, -4.8703463e-03,  2.7596310e-03,  9.9807978e-04,
       -5.8922297e-03,  5.7721538e-03, -2.4886234e-03, -6.1772298e-03,
      

In [134]:
wv.similar_by_word('movie')

[('bhai', 0.2905353307723999),
 ('kgf', 0.23018230497837067),
 ('karnataka', 0.2203635424375534),
 ('kannada', 0.21940505504608154),
 ('worst', 0.21588827669620514),
 ('loved', 0.2041063755750656),
 ('like', 0.19493022561073303),
 ('meaningless', 0.1866755187511444),
 ('compared', 0.172737717628479),
 ('put', 0.16967715322971344)]

In [135]:
import numpy as np
def sentence_vector(sent):
    doc = [word for word in sent.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc], axis=0)

In [136]:
sentence_vector(datasett['review'].values[20])

array([-4.0287825e-05, -1.0964206e-03,  9.6290844e-04,  7.0008298e-04,
       -3.1031831e-03, -4.5831958e-03, -3.8409085e-04,  2.1612982e-03,
       -3.0945629e-04, -2.3676779e-03, -1.8139889e-04, -2.2676617e-03,
       -7.6144363e-04, -1.5449509e-03,  6.2829041e-04,  1.8168493e-03,
       -3.4251253e-03, -2.4136126e-03,  2.7326569e-03, -1.3567992e-03,
       -2.6848183e-03,  2.5221605e-03,  2.0171927e-04,  1.1970055e-03,
        3.6436485e-04,  8.4452062e-05, -2.1225114e-03, -1.1038481e-03,
        1.1355717e-03,  1.2483195e-03,  1.7991337e-03, -1.1540765e-03,
        1.6563555e-03,  2.9599329e-03,  1.9691892e-03,  4.8858025e-03,
        1.6493803e-03,  1.5068164e-03, -1.8942529e-04,  4.7197280e-04,
        3.5488473e-03, -6.7536114e-04, -2.3161436e-03,  1.4022427e-03,
        1.3850193e-03, -2.3831229e-03, -8.0113747e-04,  1.2167981e-03,
       -1.6802921e-03,  1.7425532e-03,  3.0584082e-03,  1.6601451e-04,
        2.4301200e-05,  4.5783040e-03, -1.9137933e-03,  2.6643756e-04,
      

In [137]:
from tqdm import tqdm

In [140]:
final = []
for s in tqdm(datasett['review'].values):
    final.append(sentence_vector(s))

100%|█████████████████████████████████████████| 28/28 [00:00<00:00, 5246.39it/s]


In [141]:
final

[array([-2.5265615e-03,  5.4654460e-03, -7.0740248e-04,  3.6051427e-03,
         7.1342755e-03,  3.8581202e-03,  1.8958262e-03,  5.3253844e-03,
        -1.0585932e-03, -4.5609986e-04,  5.6779524e-04,  9.5082056e-03,
        -6.8076318e-03, -7.4249529e-04,  2.8190129e-03, -3.7462935e-03,
         3.3694492e-03,  2.3782589e-03,  6.3445806e-03, -2.9594658e-03,
        -5.2421959e-04,  3.3258763e-03, -7.2482103e-03,  1.7244255e-03,
         7.6341638e-03, -6.9778389e-03, -1.0325752e-03, -5.0741108e-03,
        -3.6438685e-03,  3.3223862e-04, -8.2240794e-03,  1.2509926e-03,
         2.8270003e-03, -4.8350142e-03,  2.0771320e-03,  4.0667290e-03,
         2.9651136e-03, -7.4602840e-03,  4.0238947e-03, -1.8883207e-03,
         3.1398642e-03, -1.4824320e-03,  5.5899159e-03,  1.8653763e-03,
         4.9523744e-03,  2.4005035e-03, -3.5164072e-03,  7.6560448e-03,
         2.6475405e-03, -1.9758372e-03,  2.4052248e-03,  8.1238486e-03,
        -4.7392445e-03,  2.7130749e-03,  2.1218979e-03, -4.41524