In [1]:
arr1 = ['pune',"mumbai",'surat',"kolkata",'bihar',"jaipur",'chennai']

In [2]:
type(arr1)

list

In [3]:
arr1[0]

'pune'

In [2]:
import numpy
arr2 = numpy.array([10,20,30,40,50])

In [5]:
type(arr2)

numpy.ndarray

In [6]:
print(arr2)

[10 20 30 40 50]


In [7]:
arr2

array([10, 20, 30, 40, 50])

In [8]:
arr3 = numpy.array((100,200,300,400,500))

In [9]:
type(arr3)

numpy.ndarray

In [6]:
import numpy as np
a0 = np.array(10)

In [11]:
print(a0)

10


In [12]:
a0.ndim

0

In [13]:
a0

array(10)

In [14]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [15]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a1.ndim

1

In [17]:
a2 = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])

In [18]:
a2

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [19]:
a2.ndim

2

In [20]:
a3 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]])

In [21]:
a3

array([[[   1,    2,    3],
        [  10,   20,   30]],

       [[ 100,  200,  300],
        [1000, 2000, 3000]]])

In [22]:
a3.ndim

3

In [23]:
a4 = np.array([4,44,444,4444], ndmin=4)

In [24]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [25]:
a4.ndim

4

In [26]:
amix1 = np.array(['pune',1,"mumbai",2])

In [27]:
amix1

array(['pune', '1', 'mumbai', '2'], dtype='<U21')

In [28]:
type(amix1)

numpy.ndarray

In [29]:
amix2 = np.array([True,5])

In [30]:
amix2

array([1, 5])

In [31]:
amix3 = np.array([False,10])

In [32]:
amix3

array([ 0, 10])

In [33]:
amix4 = np.array([True,'shridhar',5,5.0])

In [34]:
amix4

array(['True', 'shridhar', '5', '5.0'], dtype='<U32')

In [36]:
amix6 = np.array([False,10],dtype = np.int32)

In [37]:
amix6

array([ 0, 10], dtype=int32)

In [38]:
amix7 = np.array([1,5.55,2,6.9], dtype = np.float64)

In [39]:
amix7

array([1.  , 5.55, 2.  , 6.9 ])

In [40]:
arr1[0] 

'pune'

In [41]:
arr2[1]  [10,20,30,40,50]

20

In [42]:
arr2[0]+arr2[1]

30

In [43]:
a2[1,2] [[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]]

30

In [44]:
a2[2,2]

300

In [45]:
a3[0,0,0] [[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]]

1

In [46]:
a3[0,0,1]

2

In [47]:
a3[0,0,2]

3

In [48]:
a3[0,1,0]

10

In [49]:
a3[0,1,1]

20

In [50]:
a3[0,1,2]

30

In [51]:
a3[1,0,0]

100

In [52]:
a4[0,0,0,0]

4

In [53]:
a4[0,0,0,1]

44

In [54]:
a4[0,0,0,2]

444

In [55]:
a4[0,0,0,3]

4444

In [56]:
a4[0,0,1,0]

IndexError: index 1 is out of bounds for axis 2 with size 1

In [7]:
a12 = np.array([1,2,3])

In [12]:
a12[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [8]:
arrr = np.array([1,2,3,1,2,3,1,2,3])

In [58]:
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [59]:
arr2

array([10, 20, 30, 40, 50])

In [60]:
arr2[-1]

50

In [61]:
arr2[-2]

40

In [62]:
arr2[1:]

array([20, 30, 40, 50])

In [63]:
arr2[:3]

array([10, 20, 30])

In [64]:
arr2[:]

array([10, 20, 30, 40, 50])

In [65]:
arr2[1:4:1]

array([20, 30, 40])

In [66]:
arr2[1:4:2]

array([20, 40])

In [67]:
arr2[:4:3]

array([10, 40])

In [68]:
arr2[::4]

array([10, 50])

In [69]:
arr2[::]

array([10, 20, 30, 40, 50])

In [70]:
for i in arr2:
  print(i)

10
20
30
40
50


In [71]:
x = np.where(arr2 == 20)
print(x)

(array([1]),)


In [72]:
x = np.where(arr2 == 50)
print(x)

(array([4]),)


In [73]:
x = np.where(arrr == 2)
print(x)

(array([1, 4, 7]),)


In [74]:
arraysort = np.array([2,1,5,3,7,5,9,8,5,7,3])

In [75]:
np.sort(arraysort)

array([1, 2, 3, 3, 5, 5, 5, 7, 7, 8, 9])

In [76]:
np.insert(arr2,5,60)

array([10, 20, 30, 40, 50, 60])

In [77]:
np.insert(arraysort,11,10)

array([ 2,  1,  5,  3,  7,  5,  9,  8,  5,  7,  3, 10])

In [78]:
np.insert(arraysort,0,100)

array([100,   2,   1,   5,   3,   7,   5,   9,   8,   5,   7,   3])

In [79]:
np.delete(arraysort,0)

array([1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [80]:
arraysort

array([2, 1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [81]:
arrr1 = np.insert(arr2,5,60)

In [82]:
arrr1

array([10, 20, 30, 40, 50, 60])

In [83]:
arr2

array([10, 20, 30, 40, 50])

In [84]:
index = [0,1,2]

In [85]:
arrr2 = np.delete(arr2,index)

In [86]:
arrr2

array([40, 50])

In [87]:
arr2

array([10, 20, 30, 40, 50])

In [88]:
np.flip(arr2)

array([50, 40, 30, 20, 10])

In [89]:
arr2

array([10, 20, 30, 40, 50])

In [90]:
arrflip = np.flip(arr2)

In [91]:
arrflip

array([50, 40, 30, 20, 10])

In [92]:
arr2[0] = 100

In [93]:
arr2

array([100,  20,  30,  40,  50])

In [94]:
arr2.sort()

In [95]:
arr2

array([ 20,  30,  40,  50, 100])

In [96]:
np.append(arr2,1000)

array([  20,   30,   40,   50,  100, 1000])

In [97]:
arr2

array([ 20,  30,  40,  50, 100])

In [113]:
arr2.append(1000)

AttributeError: 'numpy.ndarray' object has no attribute 'append'